# Generated by Django 3.1.7 on 2021-03-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210317_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listen',
            name='listener',
        ),
        migrations.RemoveField(
            model_name='song',
            name='listen',
        ),
        migrations.AddField(
            model_name='listen',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listen',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
