# Generated by Django 3.1.7 on 2021-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210320_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(related_name='songs', to='api.PlayList'),
        ),
    ]
