# Generated by Django 3.1.7 on 2021-03-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210320_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='playlists',
            new_name='songs',
        ),
    ]
