# Generated by Django 3.1.7 on 2021-03-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210320_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songs',
            new_name='playlists',
        ),
    ]
