# Generated by Django 3.1.7 on 2021-03-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210320_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='User',
            new_name='users',
        ),
    ]
