# Generated by Django 3.1.7 on 2021-03-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210322_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_id',
        ),
    ]
