# Generated by Django 3.1.7 on 2021-04-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_album_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('task_1', models.BooleanField(blank=True, default=False)),
                ('task_2', models.BooleanField(blank=True, default=False)),
                ('task_3', models.BooleanField(blank=True, default=False)),
                ('task_4', models.BooleanField(blank=True, default=False)),
                ('task_5', models.BooleanField(blank=True, default=False)),
                ('task_6', models.BooleanField(blank=True, default=False)),
                ('task_7', models.BooleanField(blank=True, default=False)),
                ('task_8', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='monitor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.monitor'),
        ),
    ]
