# Generated by Django 3.1.7 on 2021-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
